apps/urls.py
from django.urls import path
from . import views

app_name = "apps"

urlpatterns = [
    path("", views.ClassListView, name="list"),
    # path("detail/<int:pk>/", views.ClassDetail.as_view(), name="detail"), 
    path('detail/<int:class_id>/', views.class_detail, name='class_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # user
    path('common/', include("common.urls")),
    path('', include("foods.urls")),
    path('group/', include("apps.urls")),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/models.py
from django.db import models
# from users import models as users_models

class TimeStampedModel(models.Model):

    """ Time Stamped Model """

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Group(models.Model):
  name = models.CharField(max_length=200)
  profile_image = models.ImageField(null=True, default="", blank=True)
  bio = models.TextField(default="", blank=True)

  class Meta:
    ordering = ['name']

  def __str__(self):
    return self.name

class Class(models.Model):
  """ Class """
  name = models.CharField(max_length=200, unique=True)
  group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True, blank=True)
  profile_image = models.ImageField(upload_to="group/image", null=True, default="", blank=True)
  bio = models.TextField(default="", blank=True)

  class Meta:
    ordering = ['name']

  def __str__(self):
    return self.name

  
  @property
  def user_count(self):
    return self.users.all().count()
    
  @property
  def user_name(self):
    return self.users.all()

templates/role/child.html
{% block content %}

<div class="ma-meals">
    <span class="ma-sub">오늘의 식사</span>
    <span class="more"><a>More</a></span>
    <div class="v264_217"></div>
    <div class="v264_218"></div>
    <div class="v264_220"></div>
    <div class="v264_221"></div>
    <div class="v264_219"></div>
</div>

<div class="ma-games">
    <span class="ma-sub">게임현황</span>
    <span class="more"><a>More</a></span>
    <div class="game-status">
        <div class="game-profile"></div>
        <div class="game-info">
            <!-- <div style="padding-left: 3.5rem;">
                <div class="gmae-point">점수</div>
                <p class="to-carbohydrate">오늘의 탄수화물</p>
                <p class="to-protein">오늘의 단백질</p>
                <p class="to-fat">오늘의 지방</p>
                <p class="game-level">Lv. 2</p>

            </div>
            <div style="padding-left: 3.5rem;">
                <p class="gmae-name">RaRa</p>
                <p class="point-increase">1.3%</p>
                <p class="game-lavel-to"></p>
                <div class="game-lavel-bar"></div>
            </div> -->




        </div>


    </div>

</div>

</div>
<div style="margin: 7.5rem; padding: 7.5;">
</div>

{% endblock %}

templates/role/select.html
{% block content %}

<style>
.select-div {
  left:12.19rem;
  top: 25rem;
  position: absolute;
}

.select {
  width: 22.5rem;
  height: 5.625rem;
  background-color: rgba(255,183,0,1);
  opacity: 1;
  position: absolute;
  border-top-left-radius: 45px;
  border-top-right-radius: 45px;
  border-bottom-left-radius: 45px;
  border-bottom-right-radius: 45px;
  box-shadow: 0px 4px 30px rgba(0, 0, 0, 0.25);
  overflow: hidden;
}

.select-1 {
  top : 6.25rem;
}

.select-2 {
  top: 15rem;
}

.select-3 {
  top: 23.75rem;
}

.select-data {
    border: 0;
    outline: 0;
    color:rgba(0, 0, 0, 0.25);
    /* background: rgba(177,242,248,1); */
    background-color: rgba(255,183,0,1);
    color: rgba(17,17,17,1);
    font-family: Roboto;
    font-weight: Bold;
    font-size: 2.5rem;
    opacity: 1;
    padding-top: 1.25rem;
    text-align: center;
}

.question {
    font-size: 2.5rem;
    font-family: Roboto;
    font-weight: Bold;
}


</style>


<div class="select-div">
    <h2 class="question">
        Q. 선택하여 주세요
    </h2>

    <div class="select  select-1">
        <button type="submit" class="select-data center-block">어린이</button>
    </div>

    <div class="select  select-2">
        <button type="submit" class="select-data center-block">선생님</button>
    </div>

    <div class="select  select-3">
        <button type="submit" class="select-data center-block">부모</button>
    </div>

</div>

{% endblock %}

templates/role/teacher.html
{% block content %}

{% include "group/group_list.html" %}

{% endblock %}