apps/urls.py
from django.urls import path
from . import views

app_name = "apps"

urlpatterns = [
    path("", views.ClassListView, name="list"),
    # path("detail/<int:pk>/", views.ClassDetail.as_view(), name="detail"), 
    path('detail/<int:class_id>/', views.class_detail, name='class_detail'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "common"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # user
    path('common/', include("common.urls")),
    path('', include("foods.urls")),
    path('group/', include("apps.urls")),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from apps import models as apps_models

class AbstractItem(apps_models.TimeStampedModel):

    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class PartClass(AbstractItem):

    """ PartClass Model Definition """

    class Meta:
        verbose_name_plural = "PartClasss"
        ordering = ["name"]


class User(AbstractUser):

    """ Custom User Model """

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"

    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
    )

    ROLE_TEACHER = "teacher"
    ROLE_CHILD = "child"
    ROLE_PARENT = "parent"

    ROLE_CHOICES = (
        (ROLE_TEACHER, "선생님"),
        (ROLE_CHILD, "어린이"),
        (ROLE_PARENT, " 부모"),
    )

    STATUS = [
      ('active', '활성화'),
      ('inactive', '비활성화')
    ]

    gender = models.CharField(choices=GENDER_CHOICES, max_length=10)
    role = models.CharField(choices=ROLE_CHOICES, max_length=10)
    profile_image = models.ImageField(upload_to="user/image", null=True, default="", blank=True)
    bio = models.TextField(default="", blank=True)
    height = models.FloatField(default=0)
    weight = models.FloatField(default=0)
    birthdate = models.DateField(null=True, blank=True)
    attend = models.IntegerField(default=0)
    current_status        = models.CharField(max_length=10, choices=STATUS, default='active')
    current_group         = models.ForeignKey(apps_models.Group, on_delete=models.SET_NULL, blank=True, null=True)
    
    main_class = models.ForeignKey(apps_models.Class, on_delete=models.SET_NULL, blank=True, null=True)

    part_class = models.ManyToManyField(apps_models.Class, related_name="users", blank=True)

    @property
    def class_count(self):
        return self.part_class.all().count()
    
    @property
    def class_name(self):
        return self.part_class.all()
    
    @property
    def attend_count(self):
        return 0

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email", "gender", "role")

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

def update(request):
    count = 0

templates/common/_common_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="UTF-8">

    <title>{% block title %}studioFood{% endblock title %}</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">

    <!-- Google Font -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <!-- jQuery 3 -->
    <script src="/static/bower_components/jquery/dist/jquery.min.js"></script>

    {% block css %}
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Custom styles CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    {% endblock %}


</head>

<body style="padding-top: 20%;">

{% include "part/_nav.html" %}
 

</body>

</html>

templates/common/login.html
{% include "common/_common_base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
        
    </form>
    <a href="{% url 'common:signup' %}"><button type="buttion" class="btn btn-primary" >회원가입</button></a>
</div>

{% endblock %}

templates/common/signup.html
{% include "common/_common_base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>회원 가입</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
        
        
            <label class="required" for="id_gender">Gender:</label>
        
            <select name="gender" required id="id_gender">
                <option value="" selected>---------</option>
        
                <option value="male">Male</option>
        
                <option value="female">Female</option>
        
            </select>
        
        </div>
        <div class="form-group">


            <label class="required" for="id_role">role:</label>

            <select name="role" required id="id_role">
                <option value="" selected>---------</option>
            
                <option value="child">어린이</option>
            
                <option value="teacher">선생님</option>
            
                <option value="parent">부모</option>
            
            </select>


        </div>

       
        
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/common/update.html
{% extends '_base.html' %}

{% block container %}

<h1>User Edit</h1>

<form method="POST">
    {% csrf_token %}

    {% bootstrap_form user_change_form %}
    <input type="submit" value="Submit" />
</form>

{% endblock %}