apps/urls.py
from django.urls import path
from . import views

app_name = "apps"

urlpatterns = [
    path("", views.ClassListView, name="list"),
    # path("detail/<int:pk>/", views.ClassDetail.as_view(), name="detail"), 
    path('detail/<int:class_id>/', views.class_detail, name='class_detail'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "common"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # user
    path('common/', include("common.urls")),
    path('', include("foods.urls")),
    path('group/', include("apps.urls")),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="UTF-8">

    <title>{% block title %}studioFood{% endblock title %}</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">

    <!-- Google Font -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <!-- jQuery 3 -->
    <script src="/static/bower_components/jquery/dist/jquery.min.js"></script>

    {% block css %}
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static '/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <link rel="stylesheet" href="{% static '/plugins/Datatables/datatables.min.css' %}" />
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static '/css/adminlte.min.css' %}">

    <!-- Custom styles CSS -->
    <link rel="stylesheet" href="{% static '/css/main.css' %}">

    {% endblock %}


</head>

<body>


    {% if request.user.is_authenticated %}
    <a class="nav-link" href="{% url 'common:logout' %}">(로그아웃)</a>
    {% if request.user.role == "teacher" %}
        <nav>
            {% include "part/_teacher_nav.html" %}
        </nav>
    
    {% else %}
        <nav>
            {% include "part/_nav.html" %}
        </nav>
    

    
    {% endif %}



        
        <footer>
            {% include "part/_footer.html" %}
        </footer>
    
    {% else %}

    <!-- !user-->

        <div class="v133_548">

            <div class="signBox center-block">
                <a href="{% url 'common:login' %}">
                <div class="v113_549"> Sign In
                </div>
                </a>

                <a href="{% url 'common:signup' %}">
                <div class="v113_549" >Sign Up</div></a>

            </div>
        
            
        </div>



    {% endif %}
    
</body>




</html>

templates/form_errors.html
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<!-- 필드 오류를 출력한다. -->
<div class="alert alert-danger">
    <strong>{{ field.label }}</strong>
    {{ error }}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<!-- 넌필드 오류를 출력한다. -->
<div class="alert alert-danger">
    <strong>{{ error }}</strong>
</div>
{% endfor %}
{% endif %}

templates/index.html
{% include "_base.html" %}

{% block content %}

{% if request.user.is_authenticated %}

<!-- request.user -->
<!-- child -->
{% if request.user.role == "child" %}

{% include "role/child.html" %}

<!-- teacher -->
{% elif request.user.role == "teacher" %}

{% include "role/teacher.html" %}

<!-- parent -->
{% elif request.user.role == "parent" %}

{% include "role/parent.html" %}

{% else %}

{% include "role/select.html" %}

{% endif %}


{% endif %}

{% endblock %}